clear

%% (0) SET UP

% IMPORTANT: SET FILE PATH TO RESULTS CSVS
results_path = 'C:\Users\neo204\OneDrive - University of Exeter\NEVO\Defra ELM\ELM Options\Runs\12-12-2019\';

mkdir([results_path, '10km'])

% Set flag for server
% -------------------
% true - NEVO
% false - local machine (for testing)
server_flag = false;

% Connect to database
% -------------------
conn = fcn_connect_database(server_flag);

% Set up scheme names
% -------------------
elm_schemes = {'fr_act', ...
               'fr_act', ...
               'fr_act', ...
               'fr_env', ...
               'fr_env', ...
               'fr_env', ...
               'fr_es', ...
               'fr_es', ...
               'fr_es', ...
               'oc', ...
               'oc', ...
               'oc', ...
               'fr_act_shared', ...
               'fr_act_shared', ...
               'fr_act_shared', ...
               'oc_shared', ...
               'oc_shared', ...
               'oc_shared'};

% Set up budgets
% --------------
elm_budgets = [1, ...
               2, ...
               3, ...
               1, ...
               2, ...
               3, ...
               1, ...
               2, ...
               3, ...
               1, ...
               2, ...
               3, ...
               1, ...
               2, ...
               3, ...
               1, ...
               2, ...
               3];
       
num_files = length(elm_budgets);

% Read in 10km grid info from database
sqlquery = 'SELECT new10kid, easting, northing FROM elm_grids.grid_defra_10km_england';
setdbprefs('DataReturnFormat','table');
dataReturn = fetch(exec(conn,sqlquery));
defra_10km_grid = dataReturn.Data;

% Read in 2km 10km grid lookup table from database
sqlquery = 'SELECT new2kid, new10kid FROM elm_grids.lookup_2km_defra_10km_grid';
setdbprefs('DataReturnFormat','table');
dataReturn = fetch(exec(conn,sqlquery));
lookup_2km_defra_10km_grid = dataReturn.Data;

% Set column names of results table to be aggregated
% --------------------------------------------------
cols_to_aggregate = {'option_hectares', ...
                     'payments', ...
                     'net_payment_to_farmer', ...
                     'benefits', ...
                     'benefit_ghg_farm', ...
                     'benefit_ghg_forestry', ...
                     'benefit_ghg_soil_forestry', ...
                     'benefit_rec', ...
                     'benefit_flooding', ...
                     'benefit_totn', ...
                     'benefit_totp', ...
                     'benefit_water_non_use', ...
                     'benefit_pollination', ...
                     'benefit_non_use_pollination', ...
                     'benefit_non_use_habitat', ...
                     'benefit_bio', ...
                     'cost_farm', ...
                     'cost_forestry', ...
                     'cost_rec', ...
                     'opp_costs', ...
                     'env_out_ghg', ...
                     'env_out_rec_grass_access', ...
                     'env_out_rec_wood_access', ...
                     'env_out_rec_grass_noaccess', ...
                     'env_out_rec_wood_no_access', ...
                     'env_out_flooding', ...
                     'env_out_totn', ...
                     'env_out_totp', ...
                     'env_out_pollination', ...
                     'env_out_bio', ...
                     'es_out_ghg', ...
                     'es_out_rec', ...
                     'es_out_flooding', ...
                     'es_out_totn', ...
                     'es_out_totp', ...
                     'es_out_water_non_use', ...
                     'es_out_pollination', ...
                     'es_out_non_use_pollination', ...
                     'es_out_non_use_habitat', ...
                     'es_out_bio'};

%% (1) LOOP OVER ALL SCHEMES AND BUDGETS
for i = 1:num_files
    % Read results .csv for this scheme and budget
    filename = [elm_schemes{i}, '_', num2str(elm_budgets(i)), '.csv'];
    results = readtable([results_path filename]);
    
    % Append new10kid to results table
    results.new10kid = lookup_2km_defra_10km_grid.new10kid;
    
    % Aggregate results to 10km grid for selected variables
    X = varfun(@sum, results, 'InputVariables', cols_to_aggregate, 'GroupingVariables', 'new10kid');
    X.Properties.VariableNames = [{'new10kid', 'num_2km_cells'}, cols_to_aggregate];
    
    % Join aggregated results to 10km grid table
    Y = outerjoin(defra_10km_grid, X, 'MergeKeys', true);
    
    % Set NaNs to 0
    Z = table2array(Y);
    Z(isnan(Z)) = 0;
    Y = array2table(Z, 'VariableNames', Y.Properties.VariableNames);
    
    % Calculate benefit-cost ratio
    Y.bcr = Y.benefits ./ Y.payments;
    Y.bcr(isnan(Y.bcr)) = 0;
    
    % Write table to .csv file in 10km folder
    writetable(Y, [results_path, '10km\', filename]);
end
