function [water_results, water_results_baseline, water_cell2sbsn] = fcn_import_water_info(conn)
    % fcn_import_water_info.m
    % =======================
    % Load data necessary for calculating non-use water quality and water 
    % quality benefits in the two_run_elm_options.m code. Specifically
    % the outputs of this function are used in fcn_run_water_from_results.m

    % (a) Load water results from .mat file
    % -------------------------------------
    load('water_results.mat', 'water_results')

    % (b) Retrieve baseline water quantities for subbsasins from database
    % -------------------------------------------------------------------
    sqlquery = ['SELECT ' ...
                    'src_id, ' ...
                    'q5_20, q5_30, q5_40, q5_50, ' ...
                    'orgn_20, orgn_30, orgn_40, orgn_50, ' ...
                    'no3_20, no3_30, no3_40, no3_50, ' ...
                    'no2_20, no2_30, no2_40, no2_50, ' ...
                    'nh4_20, nh4_30, nh4_40, nh4_50, ' ...
                    'totn_20, totn_30, totn_40, totn_50, ' ...
                    'orgp_20, orgp_30, orgp_40, orgp_50, ' ...
                    'pmin_20, pmin_30, pmin_40, pmin_50, ' ...
                    'totp_20, totp_30, totp_40, totp_50 ' ...                              
                'FROM nevo_explore.explore_subbasins ' ...
                'ORDER BY src_id'];
    setdbprefs('DataReturnFormat', 'table');
    dataReturn = fetch(exec(conn, sqlquery));
    water_results_baseline = dataReturn.Data; 

    % (c) Cell to Subbasin lookup from database
    % -----------------------------------------
    sqlquery = ['SELECT ' ...
                    'tbl1.new2kid, tbl1.src_id, tbl1.proportion, ' ...
                    'tbl2.arable_ha_20 * tbl1.proportion AS arable_ha_20, ' ...
                    'tbl2.grass_ha_20 * tbl1.proportion AS grass_ha_20 ' ...
                'FROM regions_keys.key_grid_subbasins AS tbl1 ' ...
                   'INNER JOIN nevo_explore.explore_2km AS tbl2 ' ...
                   'ON tbl1.new2kid = tbl2.new2kid ' ...
                'ORDER BY tbl1.new2kid, tbl1.src_id'];
    setdbprefs('DataReturnFormat', 'table');
    dataReturn = fetch(exec(conn, sqlquery));
    water_cell2sbsn = dataReturn.Data;
end