function [flooding_transfer_results, flooding_cell2subctch, nfm_data] = fcn_import_flooding_transfer_info(conn)
    % fcn_import_flooding_transfer_info.m
    % ===================================
    % Load data necessary for calculating flooding (transfer), non-use 
    % water quality and water quality benefits in the two_run_elm_options.m 
    % code. Specifically the outputs of this function are used in 
    % fcn_run_flooding_transfer_from_results.m

    % (a) Load flooding transfer results from .mat file
    % -------------------------------------------------
    load('Water Data/flooding_transfer_results.mat', 'flooding_transfer_results')

    % (b) Cell to subcatchment lookup from database
    % ---------------------------------------------
    sqlquery = ['SELECT ' ...
                    'tbl1.new2kid, tbl1.subctch_id, tbl1.proportion, ' ...
                    'tbl2.arable_ha_20 * tbl1.proportion AS arable_ha_20, ' ...
                    'tbl2.grass_ha_20 * tbl1.proportion AS grass_ha_20 ' ...
                'FROM regions_keys.key_grid_wfd_subcatchments AS tbl1 ' ...
                      'INNER JOIN nevo_explore.explore_2km AS tbl2 ' ...
                      'ON tbl1.new2kid = tbl2.new2kid ' ...
                'ORDER BY tbl1.new2kid, tbl1.subctch_id'];
    setdbprefs('DataReturnFormat', 'table');
    dataReturn = fetch(exec(conn, sqlquery));
    flooding_cell2subctch = dataReturn.Data;

    % (c) Natural flood management areas
    % ----------------------------------
%     sqlquery = ['SELECT ', ...
%                     'new2kid, ', ...
%                     'nfm_cell, ', ...
%                     'nfm_ha, ', ...
%                     'nfm_proportion ', ...
%                 'FROM flooding.nfm_cells_export ', ...
%                 'ORDER BY new2kid'];
%     setdbprefs('DataReturnFormat', 'table');
%     dataReturn = fetch(exec(conn, sqlquery));
%     nfm_data = dataReturn.Data;
    sqlquery = ['SELECT ', ...
                    'new2kid, ', ...
                    'nfm_cell, ', ...
                    'nfm_area_ha ', ...
                'FROM flooding.nfm_cells_gb ', ...
                'ORDER BY new2kid'];
    setdbprefs('DataReturnFormat', 'table');
    dataReturn = fetch(exec(conn, sqlquery));
    nfm_data = dataReturn.Data;
end